// <auto-generated />
namespace BurgerMenuProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class end1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(end1));
        
        string IMigrationMetadata.Id
        {
            get { return "202410310723410_end1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
